default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: empion_app_development
  username: bruno
  password:
  host: /var/run/postgresql

test:
  <<: *default
  database: empion_app_test
  username: bruno
  password:
  host: /var/run/postgresql

production:
  <<: *default
  database: empion_app_production
  username: empion
  password: <%= ENV["EMPION_DATABASE_PASSWORD"] %>
